import { StyleSheet } from 'react-native';

export const typography = StyleSheet.create({
  h1: {
    fontFamily: 'SUIT-Bold',
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 36.4,
    letterSpacing: -0.56,
  },
  h2: {
    fontFamily: 'SUIT-Bold',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 32.16,
    letterSpacing: -0.48,
  },
  h3: {
    fontFamily: 'SUIT-Bold',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 28.4,
    letterSpacing: -0.4,
  },
  h4: {
    fontFamily: 'SUIT-Bold',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 24,
    letterSpacing: -0.32,
  },
  large500: {
    fontFamily: 'SUIT-Medium',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 27.72,
    letterSpacing: -0.36,
  },
  large400: {
    fontFamily: 'SUIT-Regular',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 27.72,
    letterSpacing: -0.36,
  },
  medium500: {
    fontFamily: 'SUIT-Medium',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 24,
    letterSpacing: -0.32,
  },
  medium400: {
    fontFamily: 'SUIT-Regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 24,
    letterSpacing: -0.32,
  },
  small500: {
    fontFamily: 'SUIT-Medium',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 19.88,
    letterSpacing: -0.28,
  },
  small400: {
    fontFamily: 'SUIT-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 19.88,
    letterSpacing: -0.28,
  },
  exSmall500: {
    fontFamily: 'SUIT-Medium',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 18,
    letterSpacing: -0.24,
  },
  exSmall400: {
    fontFamily: 'SUIT-Regular',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 18,
    letterSpacing: -0.24,
  },
});
